// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://legbmkgelplurbzsejqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlZ2Jta2dlbHBsdXJienNlanFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODYyMzAsImV4cCI6MjA3MTY2MjIzMH0.DQbt5tCEA_ERJDIaeZvl3OMvev4UTvb_Ry0DDmX_ap0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});